name: Run Aggeregate Index Algolia

# for development and testing, use this
# on: push

on:
  schedule:
    # daily at 00:42 Pacific = 07:42 UTC (42m is to be outside any high load times)
    - cron: '42 7 * * *'

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          AlGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_NAME: ${{ secrets.ALGOLIA_APP_NAME }}
          ALGOLIA_SINGLE_ENTRY_INDEX: ${{ secrets.ALGOLIA_SINGLE_ENTRY_INDEX }}
          ALGOLIA_AGGREGATED_INDEX: ${{ secrets.ALGOLIA_AGGREGATED_INDEX }}
        run: node scripts/aggregate-index.js